version: 2
jobs:
  build:
    docker:
      - image: circleci/<使うやつ>
    steps:
      - checkout
      - run: bash generate-readme.sh
      - run: git config user.name "CircleCI"
      - run: git config user.email "circleci@gh.com"
      - run: git add README.md
      - run: git commit -m 'Update README.md [ci skip]'
      - run: git push origin master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
